// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Creature struct {
	ID   string `json:"id" bson:"_id,omitempty"`
	Name string `json:"name" bson:"name"`
}

type NewCreature struct {
	Name      string `json:"name" bson:"name"`
	SpeciesID string `json:"speciesId" bson:"speciesId"`
}
