package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/ataboo/fish-roster/fish-roster-api/graph/model"
)

// CreateCreature is the resolver for the createCreature field.
func (r *mutationResolver) CreateCreature(ctx context.Context, input model.NewCreature) (*model.Creature, error) {
	return r.CreatureRepo.Create(input.Name)
}

// DeleteCreature is the resolver for the deleteCreature field.
func (r *mutationResolver) DeleteCreature(ctx context.Context, id string) (bool, error) {
	return r.CreatureRepo.Delete(id)
}

// Creatures is the resolver for the creatures field.
func (r *queryResolver) Creatures(ctx context.Context) ([]*model.Creature, error) {
	return r.CreatureRepo.FindAll()
}

func (r *queryResolver) Creature(ctx context.Context, id string) (*model.Creature, error) {
	return r.CreatureRepo.Find(id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
